### ISSUE TITLE
GetSigningCredentials should throw Exception if Certificate is null

### ISSUE THREAD

**Issue by rzontar** [IdentityModel/AuthorizationServer#247]
Apparently if a Certificate is not found, perhaps due to misconfiguration, `null` is returned for the SigningCredentials. This causes the JwtToken not to bo signed at all. This is unexpected behavior to me and could compromise the AuthorizationServer.

I would suggest changing the following code: 
        public override SigningCredentials GetSigningCredentials()
        {
            var cert = this.Certificate;
            if (cert == null) return null;
            return new X509SigningCredentials(cert);
        }
to something like this:
        public override SigningCredentials GetSigningCredentials()
        {
            var cert = this.Certificate;
            if (cert == null) throw new Exception("No certificate could be found");
            return new X509SigningCredentials(cert);
        }

**Comment by leastprivilege** [comment]
sure - feel free to change it.
