### ISSUE TITLE
OAuth2 Flow Sample Walkthrough <Question>

### ISSUE THREAD

**Issue by simplynewbie** [IdentityModel/AuthorizationServer#250]
I'm a newbie in Oauth2 and i try to learn by doing step-by-step from videos but sometimes code is not same as video.

Video: AuthorizationServer- OAuth2 Flows Samples Walkthrough
File project: AuthorizationServer-master

Example: 
* ClientCredentials Flow: 
In the video, it's only CallService(RequestToken()) 
but it's CallService(RequestToken().AccessToken) in the project

Maybe it's not important but i have this problem:
- When i try debug the project, it has an error 
![ask2](https://cloud.githubusercontent.com/assets/13635626/9055167/58e34636-3ab2-11e5-99bd-6119a50e34d5.png)

![ask3](https://cloud.githubusercontent.com/assets/13635626/9058506/df6de8aa-3acb-11e5-8baf-fdbe2e9821e9.png)

- When i try changing code as same as video, it has an other error
![ask1](https://cloud.githubusercontent.com/assets/13635626/9055173/5ffd1460-3ab2-11e5-9435-2743b56827db.png)

Please tell me how to edit? Thank you.

**Comment by brockallen** [comment]
If you're new to using OAuth2 and are looking to build an authorization server, I'd recommend using IdentityServer3 -- it's the project that's currently supported.

**Comment by simplynewbie** [comment]
thank you, i'll learn IdentityServer3, too. But now my master want me to investigate IdentityServer2.

**Comment by simplynewbie** [comment]
brockallen, i have a problem with Resource Owner Password Flow
(pic0)
![z3](https://cloud.githubusercontent.com/assets/13635626/9082534/ef836f6c-3b8e-11e5-8882-c7a230311bca.png)

I read #55 and #124 . I try editting autofac.config as #55 by copy paste:
(pic1)
![z1](https://cloud.githubusercontent.com/assets/13635626/9082516/cc2e8966-3b8e-11e5-93c4-9b4fa29974cb.png)

(pic2)
![z2](https://cloud.githubusercontent.com/assets/13635626/9082524/d93b58f0-3b8e-11e5-93f2-ce641c3bcfac.png)

But pic0 still happens. I don't clearly understand #124 comments. If i'm wrong, can you explain what are those username and password and how i could find them?
