### ISSUE TITLE
Make an existing web API be a resource server <question>

### ISSUE THREAD

**Issue by simplynewbie** [IdentityModel/AuthorizationServer#251]
I created an web API to search databases from SQL Server, now i want to "transform" it to be a resource server (such as web API v1 in Samples - Oauth2 Flows solution). 
Can you tell me where i need change? (example: config , controller, model.. etc).  
I'm using thinktecture IdentityServer v2.5, your AuthorizationServer-master. 

I tried to include my project and copy paste ViewClaim.cs to its models but 
"using System.Security.Claims;" can not work. I can not find Reference to it.

![vv](https://cloud.githubusercontent.com/assets/13635626/9108729/3ffa8f90-3c5a-11e5-9bdc-864b71fe8fbe.png)

**Comment by brockallen** [comment]
I don't follow -- you have a custom API that you now want to secure?

**Comment by simplynewbie** [comment]
yes, exactly, with Oauth2 IdentityServer2 :D

**Comment by simplynewbie** [comment]
And can you explain or give me a link which show me how security of your resource server work? It's best if i can read. I'm very bad at hearing. Thank you.

**Comment by brockallen** [comment]
You're getting a 404 as the status code it seems -- that means you're not even hitting the correct URL for your service.

**Comment by simplynewbie** [comment]
ok i change "identity" to my api link, it's no error now. But the last problem, 
as i understand, AuthorizationServer sends request CallService to ResourceServer and RS returns some informations to AS. It's means the link service is existing, I built resource server in IIS, so when i copy paste the link, it's still active without security. 

example: www.test.com/api/search?name=Sim

www.test.com is 127.0.0.1
"/api/search?name=Sim" is like "identity" in your project.
Use your Flow samples, it's ok in both tokens and service results

But i login or logout IdentityServer / AuthorizationServer, 
"www.test.com/api/search?name=Sim" still show the result. 

=> Can i check the security (Oauth2) in the same computer?

**Comment by simplynewbie** [comment]
thank you, i found and edited "identity" to my api service link and it's ok. :D

I try to add my project to your ResourceServer web_api_v1 and paste to a new folder and bind to another port. And i have this problems about SSL:
"The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel" 

If i use selfssl tool, it happens in Request Tokens:
-  var response = client.RequestResourceOwnerPasswordAsync("dominick", "123@abc", "read").Result;

If i use normal self-certificate, it happens in Calling service:
-  var response = client.GetAsync("api/content/search/?name=Sim&age=15").Result;

i added certificate to trust root and shared to network service, too.
![xz](https://cloud.githubusercontent.com/assets/13635626/9242014/79755e08-41a5-11e5-84c1-ba9e2ebd270d.png)

![xc](https://cloud.githubusercontent.com/assets/13635626/9242018/89c04228-41a5-11e5-91cd-707bf7276a81.png)

but it's still 
![xx](https://cloud.githubusercontent.com/assets/13635626/9241992/13bbe3c0-41a5-11e5-83df-6c784c28b9f2.png)

https://www.think.com/api/content/search/?name=Sim&age=15 normally shows result.
content is {controller}, search is {action}
https://www.think.com/authz/Admin/Global (and other links) normally works

Can you help me more? And pls show me the security endpoint of your ResourceServer web api v1. 
Thank you.

**Comment by brockallen** [comment]
I'm sorry, I just don't understand what the question is related to AuthorizationServer. We don't do consulting here in github, we answer questions about the OSS.

**Comment by simplynewbie** [comment]
OK, i'm sorry about this. Thank you so much for helping.
