### ISSUE TITLE
Get code from Code Flow (client request)

### ISSUE THREAD

**Issue by simplynewbie** [IdentityModel/AuthorizationServer#252]
Excute me, can you show me exactly the link after click Allow from: 
![yyyy](https://cloud.githubusercontent.com/assets/13635626/9806985/a1d087b4-5876-11e5-8307-62a38ef447cf.png)

to get the code. I use WPF client and i try this code: 
![yyyi](https://cloud.githubusercontent.com/assets/13635626/9807131/f1474f88-5878-11e5-8cd8-fdf5c6361999.png)
__
I plays the debug (of your code flow sample) and it shows code in ViewBag.Code but i don't know how it can return that code. 

And where i can change this url "https://localhost:44303/callback" of Code Flow? I mean only text, example: http://abc.com/callback

**Comment by simplynewbie** [comment]
I dont know why but today i can not upload image or edit comment here so i comment this:
__ I try:
private void WBrowser_OnNavigated(object sender, NavigationEventArgs e)
{
     if (e.Uri.ToString().StartsWith("the-link-after-clicking-ALLOW")) //
     {                
	   // Is the-link-after-clicking-Allow https://localhost:44303/callback?code=... ?
	   // If yes, i'll try this: 
          CodeToken = e.Uri.Fragment.Split('?')[0].Replace("code=", "");
	   // ... 
     }
}

**Comment by leastprivilege** [comment]
We don't do any active support anymore. Think of AS as a sample.

You need to debug your way through yourself.

**Comment by simplynewbie** [comment]
thank you, i'm sorry :(

**Comment by simplynewbie** [comment]
thank you, i'm sorry :(

**Comment by simplynewbie** [comment]
thank you, i'm sorry :(
