### ISSUE TITLE
the remote certificate is invalid according to the validation 

### ISSUE THREAD

**Issue by pagidigovardhan** [IdentityModel/AuthorizationServer#256]
I am new to Thinktecture..:) 
I tried the sample MVC authentication form Github and I installed the certificate (Improted in personal and trusted as well) still it throws this error on click of  Login (https://hostname/Home/About)
Can anybody help me on this???

**Comment by brockallen** [comment]
I'd suggest watching the first module on how SSL and certificates work from Dominick's pluralsight web api course.

**Comment by pagidigovardhan** [comment]
I resolved this using test certificate provided by IdSrv, Thanks
I am closing this issue.
